{% set name = "django-groups-manager" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-groups-manager-{{ version }}.tar.gz
  sha256: fcc099ac8ce8efc1a620f679728d26de1f9cc8068482b9cfb06bfef1d08ad3a8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - jsonfield
    - pip
  run:
    - python >={{ python_min }}
    - django >=3.2
    - django-mptt

test:
  imports:
    - groups_manager
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/vittoriozamboni/django-groups-manager
  summary: Django groups manager through django-mptt.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
